# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://mikechilson.com'

# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
# baseurl: 'https://mchilson.github.io/website' # use this one when deploying
baseurl: ''

# Title of the Site
title: Mike Chilson
# Description of the Site
description: Freelance Software Developer/Engineer
# URL of Image of the Site
site-image: ../assets/images/meta.jpg
# Keywords of the Site
site-keywords: Freelance, Programming, Software Solutions, Software Development, Technical Tips
# URL for the Image of custom Favicon
favicon-url: assets/images/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: ../images/4280758_1920.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: rcsbguy@protonmail.com
twitter_username: MikeChilson9
github_username:  mchilson
youtube_channel_id: UC2gX0fPOjIe5mBmT2QASwjQ
linkedin_username: mike-chilson-al

# Google Analytics
# google-analytics: UA-163806439-1

# Disqus
disqus-shortname: website-Fjm3BuUzy0

# Name of the Author
author-name: Mike Chilson
# URL for the Image of the Author
author-image: assets/images/mike_new.jpg
# 60 Words About the Author
author-about-1: I am a freelance software developer with over 45 years of experience based in Birmingham, Alabama. I currently work within web-based technologies with a specialization in full-stack web applications, and server-side API's. I have a broad background in platform specific software development in the manufacturing, healthcare, transportation, mining and service industries, both platform-specific applications and web-based ones. Check out my Portfolio on the site menu for some examples of my recent work.
author-about-2: Something that sets me apart from most contract developers is I do value-based pricing. That simply means I don't force an hourly rate on projects but try to give a client a fixed cost once the deliverables are agreed upon. This shares the risk with the client making them a happy long-term returning customer when their project is delivered within budget.
author-about-3: I am fluent in C/C++, PHP, Ruby, R, and of course HTML, CSS/SCSS, and Javascript. I regularly use the following frameworks... Rails, Sinatra, and Jekyll for Ruby. Shiny and Plumber in R. I also have working knowledge of SQL with the following database servers PostgreSQL, MS SQL Server, MySQL, and SQLite.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://mikechilson.com

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

jekyll_admin:
  homepage: "pages"

